image:
  repository: mesosphere/kommander
  defaultTag: "{{ .Chart.AppVersion }}"
  # add this to override default tag: 1.184.0-beta.something
  pullPolicy: IfNotPresent
replicas: 1
logoutRedirectPath: /ops/landing
clusterPollingIntervalFast: 10000
clusterPollingIntervalMedium: 60000
clusterPollingIntervalSlow: 120000
clusterPollingStaggerFactor: 2
hostPollingInterval: 3000
kubernetesVersionsSelection: '["1.16.4", "1.16.3"]'
kubeaddonsAddress: kommander-kubeaddons-kubeaddons-catalog

# Mode must be either production|konvoy
mode: production

displayName: Kommander Cluster

extraInitContainers:

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 6
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 6

### This must match the serviceName set in the ingress backend below
service:
  name: kommander

ingress:
  traefikFrontendRuleType: PathPrefixStrip
  extraAnnotations:
    traefik.ingress.kubernetes.io/priority: "2"
    traefik.ingress.kubernetes.io/auth-type: forward
    traefik.ingress.kubernetes.io/auth-url: http://traefik-forward-auth-kubeaddons.kubeaddons.svc.cluster.local:4181/
    traefik.ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
  path: /ops/portal/kommander/ui
