apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-operator.fullname" . }}-config-logging
  labels:
    app.kubernetes.io/part-of: knative-operator
    operator.knative.dev/release: v1.9.3
  {{- include "knative-operator.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configLogging.Example | toYaml | indent 1 }}