apiVersion: v1
name: kommander-lifecycle-controller
appVersion: "0.1.0"
version: 0.1.0
description: A controller that will be responsible for the lifecycle of the KommanderCore resource.
maintainers:
  - name: azhovan
