apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-admin
  labels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - workspaces.kommander.mesosphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kommander.mesosphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - core.kubefed.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - types.kubefed.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-edit
  labels:
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - workspaces.kommander.mesosphere.io
  resources:
  - projects
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kommander.mesosphere.io
  resources:
  - cloudprovideraccounts
  - konvoyclusters
  - kommanderclusters
  - licenses
  - virtualgroups
  - virtualgrouprolebindings
  - virtualgroupclusterrolebindings
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - workspaces.kommander.mesosphere.io
  resources:
    - projects/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
  - kommander.mesosphere.io
  resources:
  - cloudprovideraccounts/status
  - konvoyclusters/status
  - kommanderclusters/status
  - licenses/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-view
  labels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - workspaces.kommander.mesosphere.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kommander.mesosphere.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kubefed.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - types.kubefed.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
