apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-webhook
  labels:
    {{- include "kommander-cluster-lifecycle.commonLabels" . | nindent 4 }}
    control-plane: {{ template "kommander-cluster-lifecycle.fullname" . }}-webhook
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kommander.mesosphere.io
  resources:
  - konvoyclusters
  - cloudprovideraccounts
  verbs:
  - get
- apiGroups:
  - kommander.mesosphere.io
  resources:
  - virtualgroups
  - virtualgroupclusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workspaces.kommander.mesosphere.io
  resources:
  - workspaces
  - virtualgroupworkspacerolebindings
  - virtualgroupprojectrolebindings
  verbs:
  - get
  - list
  - watch
