---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedAddon
metadata:
  name: reloader
  namespace: kubeaddons
spec:
  placement:
    clusterSelector:
      matchExpressions:
        - {key: kommander.mesosphere.io/cluster-type, operator: Exists, values: []}
        - {key: kommander.mesosphere.io/cluster-type, operator: NotIn, values: [Konvoy]}
  template:
    metadata:
      labels:
        kubeaddons.mesosphere.io/name: reloader
    spec:
      chartReference:
        chart: reloader
        repo: https://stakater.github.io/stakater-charts
        values: |
          ---
          reloader:
            deployment:
              resources:
                limits:
                  cpu: "100m"
                  memory: "512Mi"
                requests:
                  cpu: "100m"
                  memory: "128Mi"
        version: v0.0.49
      kubernetes:
        minSupportedVersion: v1.15.6
