---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedAddon
metadata:
  name: opsportal-addons-kommander-overrides
  namespace: kubeaddons
spec:
  placement:
    clusterSelector:
      matchLabels: {}
  template:
    metadata:
      # We have to place these route overrides in the kubeaddons namespace since that is where the service resides.
      # This is not ideal since we would like to simply delete the kommander-system namespace when clusters
      # leave federation.
      # TODO (jr): investigate a better way to solve for this. Creating an Service of type externalName perhaps.
      namespace: kubeaddons
      labels:
        kubeaddons.mesosphere.io/name: opsportal-addons-kommander-overrides
    spec:
      chartReference:
        chart: generic-ingress
        repo: https://mesosphere.github.io/charts/staging
        version: 0.1.1
        values: |
          ---
          ingresses:
          - name: ui
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.frontend.rule.type: PathPrefixStrip
              traefik.ingress.kubernetes.io/priority: "2"
              traefik.ingress.kubernetes.io/auth-type: forward
              traefik.ingress.kubernetes.io/auth-url: http://traefik-forward-auth-kommander-kubeaddons.kommander-system.svc.cluster.local:4181/
              traefik.ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
            paths:
              # portal:
              - backend:
                  serviceName: opsportal
                  servicePort: 80
                path: /ops/portal
          - name: dashboards
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.frontend.rule.type: PathPrefixStrip
              traefik.ingress.kubernetes.io/priority: "3"
              traefik.ingress.kubernetes.io/auth-type: forward
              traefik.ingress.kubernetes.io/auth-url: http://traefik-forward-auth-kommander-kubeaddons.kommander-system.svc.cluster.local:4181/
              traefik.ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
            paths:
              # kibana
              - backend:
                  serviceName: kibana-kubeaddons
                  servicePort: 5601
                path: /ops/portal/kibana
              # grafana
              - backend:
                  serviceName: prometheus-kubeaddons-grafana
                  servicePort: 3000
                path: /ops/portal/grafana
              # prometheus
              - backend:
                  serviceName: prometheus-kubeaddons-prom-prometheus
                  servicePort: 9090
                path: /ops/portal/prometheus
              # alertmanager
              - backend:
                  serviceName: prometheus-kubeaddons-prom-alertmanager
                  servicePort: 9093
                path: /ops/portal/alertmanager
              # traefik
              - backend:
                  serviceName: traefik-kubeaddons-dashboard
                  servicePort: 80
                path: /ops/portal/traefik
      cloudProvider:
      - enabled: true
        name: aws
      - enabled: true
        name: azure
      - enabled: true
        name: docker
      - enabled: true
        name: none
      kubernetes:
        minSupportedVersion: v1.15.0
      requires:
      - matchLabels:
          kubeaddons.mesosphere.io/provides: ingresscontroller
