---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedClusterAddon
metadata:
  name: cert-manager
spec:
  placement:
    clusterSelector:
      matchExpressions:
        - {key: kommander.mesosphere.io/cluster-type, operator: Exists, values: []}
        - {key: kommander.mesosphere.io/cluster-type, operator: NotIn, values: [Konvoy]}
  template:
    metadata:
      labels:
        kubeaddons.mesosphere.io/name: cert-manager
    spec:
      chartReference:
        chart: cert-manager-setup
        repo: https://mesosphere.github.io/charts/staging
        values: |
          ---
          issuers:
            - name: kubernetes-root-issuer
              secretName: kubernetes-root-ca

          certificates:
            - name: kubernetes-intermediate-ca
              secretName: kubernetes-intermediate-ca
              issuerRef:
                name: kubernetes-root-issuer
                kind: Issuer
                # These are the default usages for reference
                usages:
                  - "digital signature"
                  - "key encipherment"
              commonName: cert-manager
              duration: 87600h
              dnsNames: []

          clusterissuers:
            - name: kubernetes-ca
              spec:
                ca:
                  secretName: kubernetes-intermediate-ca
        version: 0.1.8
      cloudProvider:
      - enabled: true
        name: aws
      - enabled: true
        name: azure
      - enabled: true
        name: gcp
      - enabled: true
        name: docker
      - enabled: true
        name: none
      kubernetes:
        minSupportedVersion: v1.15.6
      namespace: cert-manager
