---
apiVersion: core.kubefed.io/v1beta1
kind: FederatedTypeConfig
metadata:
  finalizers:
  - core.kubefed.io/federated-type-config
  generation: 1
  name: clusterrolebindings.rbac.authorization.k8s.io
  labels:
    {{- include "kommander-cluster-lifecycle.commonLabels" . | nindent 4 }}
spec:
  federatedType:
    group: types.kubefed.io
    kind: FederatedClusterRoleBinding
    pluralName: federatedclusterrolebindings
    scope: Cluster
    version: v1beta1
  propagation: Enabled
  targetType:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    pluralName: clusterrolebindings
    scope: Cluster
    version: v1
