---
apiVersion: core.kubefed.io/v1beta1
kind: FederatedTypeConfig
metadata:
  finalizers:
  - core.kubefed.io/federated-type-config
  generation: 1
  name: rolebindings.rbac.authorization.k8s.io
  labels:
    {{- include "kommander-cluster-lifecycle.commonLabels" . | nindent 4 }}
spec:
  federatedType:
    group: types.kubefed.io
    kind: FederatedRoleBinding
    pluralName: federatedrolebindings
    scope: Namespaced
    version: v1beta1
  propagation: Enabled
  targetType:
    group: rbac.authorization.k8s.io
    kind: RoleBinding
    pluralName: rolebindings
    scope: Namespaced
    version: v1
