apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
data:
  {{- (.Files.Glob "default-resources/*.yaml").AsConfig | nindent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-wait-apiservices
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
      containers:
      - name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
        image: "bitnami/kubectl:1.16.2"
        command: [
          "kubectl", "wait", "--for=condition=Available", "--timeout=300s", "apiservice",
          "v1alpha1.webhook.workspaces.kommander.mesosphere.io",
          "v1beta1.webhook.kommander.mesosphere.io"
        ]
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
      containers:
        - name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
          image: "bitnami/kubectl:1.16.2"
          volumeMounts:
            - name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
              mountPath: /etc/{{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
              readOnly: true
          command: ["kubectl", "apply", "-f", "/etc/{{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources"]
      volumes:
        - name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
          configMap:
            name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
      restartPolicy: OnFailure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["workspaces.kommander.mesosphere.io"]
    resources: ["workspaces", "workspaceroles", "virtualgroupworkspacerolebindings"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: ["apiregistration.k8s.io"]
    resources: ["apiservices"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
subjects:
  - kind: ServiceAccount
    name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kommander-cluster-lifecycle.fullname" . }}-default-resources
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
