{{- range .Values.storageclasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  annotations:
{{- if .isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
    kubernetes.io/description: Local volume provisioner StorageClass ({{ .name }})
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: {{ .volumeBindingMode | quote }}
reclaimPolicy: {{ .reclaimPolicy | quote }}
{{- end }}
