apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knative-serving.fullname" . }}-webhook-certs
  labels:
    app.kubernetes.io/component: webhook
  {{- include "knative-serving.labels" . | nindent 4 }}