apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeaddons-catalog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kubeaddons-catalog.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "kubeaddons-catalog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
